# Generated by Django 3.1.3 on 2020-11-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='x',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='y',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='del_man',
            name='x',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='del_man',
            name='y',
            field=models.FloatField(default=''),
        ),
    ]
