# Generated by Django 3.1.3 on 2020-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20201120_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='del_man',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='del_man',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_3',
            field=models.IntegerField(default=0),
        ),
    ]
