# Generated by Django 3.1.3 on 2020-11-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20201120_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '고객', 'verbose_name_plural': '고객'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
