# Generated by Django 3.1.3 on 2020-11-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20201120_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='del_man',
            options={'verbose_name': '배달원', 'verbose_name_plural': '배달원'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': '배달정보', 'verbose_name_plural': '배달정보'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '고객사', 'verbose_name_plural': '고객사'},
        ),
        migrations.AlterModelTable(
            name='del_man',
            table='DeliveryMan',
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='Delivery',
        ),
        migrations.AlterModelTable(
            name='store',
            table='Store',
        ),
    ]
