# Generated by Django 3.1.3 on 2020-11-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20201120_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='orderd_items',
        ),
        migrations.AddField(
            model_name='delivery',
            name='num_item_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='num_item_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='num_item_3',
            field=models.IntegerField(default=0),
        ),
    ]
