# Generated by Django 3.1.3 on 2020-11-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20201120_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='item_3',
        ),
        migrations.AddField(
            model_name='store',
            name='detailed_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='new_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='old_address',
            field=models.TextField(default=''),
        ),
    ]
