# Generated by Django 3.1.3 on 2020-11-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20201120_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Item_Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.store')),
            ],
            options={
                'verbose_name': '고객사별 상품수',
                'verbose_name_plural': '고객사별 상품수',
                'db_table': 'Item_Store',
            },
        ),
    ]
