# Generated by Django 3.1.3 on 2020-11-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20201120_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='detailed_address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='new_address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='old_address',
        ),
    ]
